export interface ResourceLink {
  title: string;
  url: string;
  description?: string;
  isActive?: boolean;
  tags?: string[];
}

export interface ResourceCategory {
  id: string;
  title: string;
  links: ResourceLink[];
}

export const resourceData: ResourceCategory[] = [
  {
    id: "vedic-wisdom",
    title: "Vedic Wisdom",
    links: [
      { title: "Bhakti Vedanta", url: "https://vedabase.io/", isActive: true, description: "A comprehensive digital library for the works of A.C. Bhaktivedanta Swami Prabhupada and the Gaudiya Vaishnava tradition." },
      { title: "Maharishi International University", url: "https://vedicreserve.miu.edu/", isActive: true, description: "A repository of the extensive Vedic Literature collection preserved by Maharishi Mahesh Yogi's organization." },
      { title: "Ramayana - Critical Edition", url: "https://www.valmikiramayan.net/", isActive: true, description: "A detailed, verse-by-verse presentation of the Valmiki Ramayana, including Sanskrit text and English translations." },
      { title: "Bhagavad Gita - Vaishnava Sampradaya", url: "https://www.bhagavad-gita.org/", isActive: true, description: "A scholarly presentation of the Bhagavad Gita according to the four authentic Vaishnava successions." },
      { title: "Swami Prabhupada - Bhagavad Gita As It Is", url: "https://www.asitis.com/", isActive: true, description: "The world's most widely read edition of the Gita, with original Sanskrit, word-for-word meanings, and elaborate purports." },
      { title: "Mahabharat & Related Stories", url: "https://www.mahabharataonline.com/", isActive: false, description: "A digital hub for the Mahabharata epic, offering stories, character details, and thematic analysis." },
      { title: "Mahabharata Resources", url: "https://www.mahabharata-resources.org/", isActive: false, description: "A collaborative resource for scholars and students of the Mahabharata and related Puranic literature." },
      { title: "Wisdom of Tantrik Tradition", url: "https://www.shivashakti.com/", isActive: true, description: "Exploration of the Shiva-Shakti traditions, including Tantra, Yoga, and Kashmiri Shaivism." },
      { title: "Vatsayana - Kama Sutra", url: "https://www.kamasutra-sex.org/", isActive: false, description: "An authentic translation of the ancient Sanskrit text on human behavior and ethics." },
      { title: "Sanskrit Documents' Collection", url: "https://www.sanskritdocuments.org/", isActive: true, description: "A massive archive of Sanskrit texts in various formats (ITRANS, PDF, Devanagari) across all branches of literature." },
      { title: "Vedic Documents - Stiehl's Collection", url: "https://www.sanskritweb.net/", isActive: true, description: "High-quality PDF editions of major Vedic Samhitas and Brahmanas, typeset with accentuation." },
      { title: "Sanskrit Texts and Stotras", url: "https://sanskrit.safire.com/", isActive: true, description: "A curated collection of popular stotras and technical Sanskrit treatises." },
      { title: "English Translations of Vedic Scriptures", url: "https://www.hinduwebsite.com/", isActive: true, description: "Extensive translations and articles on Hinduism, Buddhism, Jainism, and Sikhism." },
      { title: "Vedic Sacred Texts", url: "https://www.sacred-texts.com/hin/", isActive: true, description: "A global archive of world religion and mythology texts, with a strong focus on Hindu scriptures." },
      { title: "Online Spiritual Library", url: "https://www.celextel.org/", isActive: true, description: "A digital library focusing on the Upanishads and works of Adi Shankaracharya." },
      { title: "Vedas and Puranas In Hindi", url: "http:s//www.vedpuran.com/", isActive: true, description: "Accessible Hindi translations of the four Vedas and major Maha-Puranas." },
      { title: "Sanskrit English online translation", url: "https://www.spokensanskrit.de/", isActive: false, description: "A powerful, bidirectional Sanskrit-English dictionary and grammar reference." },
      { title: "Shri Madhvacharya's Doctrine", url: "https://www.dvaita.org/", isActive: true, description: "The primary resource for Dvaita Vedanta philosophy as propounded by Sri Madhvacharya." },
      { title: "Introduction to Advaita Vedanta", url: "https://www.advaita-vedanta.org/", isActive: true, description: "Scholarly introductions and discussions on the non-dualistic philosophy of Advaita." },
      { title: "Gateway To Advaita Vedanta", url: "https://www.shankaracharya.org/", isActive: true, description: "Dedicated to the life and works of Adi Shankaracharya, the primary teacher of Advaita." },
      { title: "Sri Sathya Sai Veda Pratishtan", url: "https://www.vedamu.org/", isActive: true, description: "An educational portal dedicated to Vedic chanting and the preservation of Vedic knowledge." },
      { title: "Sri Aurobindo Kapali Sastry Institute", url: "https://www.vedah.com/", isActive: true, description: "Research and publications on the deeper esoteric meaning of the Vedas based on Sri Aurobindo's vision." },
      { title: "Satguru Sivaya Subramuniyaswami", url: "https://www.himalayanacademy.com/", isActive: true, description: "Resources from the Kauai Hindu Monastery, including Hinduism Today magazine and educational books." },
      { title: "Understanding Vedic Culture", url: "https://www.hinduism.co.za/", isActive: true, description: "A thematic exploration of Vedic culture and philosophy for modern audiences." },
      { title: "Sanatan Dharma Information", url: "https://www.urday.com/", isActive: true, description: "Introductory information on Sanatana Dharma protocols, festivals, and philosophies." },
      { title: "The Hindu Encyclopedia", url: "https://www.hindupedia.com/", isActive: true, description: "A community-driven wiki for comprehensive information on all aspects of Hinduism." },
      { title: "A Hindu Blog", url: "https://www.hindu-blog.com/", isActive: true, description: "Daily updates on Hindu news, festivals, and spiritual insights." },
      { title: "Buddha Dharma Education Association", url: "https://www.buddhanet.net/", isActive: true, description: "Global Buddhist network providing educational resources and meditation guides." },
      { title: "Jainism Global Resource Center", url: "https://www.jainworld.com/", isActive: true, description: "Comprehensive library for Jain philosophy, history, and practice." },
    ],
  },
  {
    id: "international-vedic",
    title: "International Vedic Culture",
    links: [
      { title: "Russian Vedic Culture", url: "https://www.gauranga.org/vedic.htm", isActive: false },
      { title: "World Vedic Influence", url: "https://personalpages.tds.net/~theseeker/Ts.htm", isActive: false },
      { title: "Abraham - The Brahmin", url: "https://www.mondovista.com/abraham.html", isActive: true , description: "Viewzone Magazine offers a look at life and humanity from different angles. Conspiracies, lost history, religion and mysteries as well as humor and facts... we tell it like it is." },
      { title: "Noah - From Vedic Flood Stories", url: "https://www.mondovista.com/noah.story.html", isActive: true , description: "Viewzone Magazine offers a look at life and humanity from different angles. Conspiracies, lost history, religion and mysteries as well as humor and facts... we tell it like it is." },
      { title: "Vedic Civilization Spread", url: "https://www.vedicempire.com/", isActive: false },
      { title: "Hare Krishna Spiritual Resource Network", url: "https://www.salagram.net/", isActive: false },
    ],
  },
  {
    id: "vedic-intellectuals-indian",
    title: "Vedic Intellectuals (Indian)",
    links: [
      { title: "Vivekananda's Views", url: "https://www.vivekanandagospel.org/", isActive: true },
      { title: "Works of Ramakrishna and Vivekananda", url: "https://www.ramakrishnavivekananda.info/", isActive: true },
      { title: "Sri Aurobindo Ashram", url: "https://www.sriaurobindoashram.info/", isActive: true , description: "This is the website of Sri Aurobindo Ashram, a community in Pondicherry, South India." },
      { title: "Kanchi Kamakoti Peetham - Official", url: "https://www.kamakoti.org/", isActive: true , description: "One of the largest resources for Hinduism and Advaita Vedanta, running into several thousands of pages. Includes content in English, Tamil, Hindi, Sanskrit, Telugu, தெய்வத்தின் குரல் (Deivathhin Kural) in Tamil" },
      { title: "Mata Amritanandamayi Devi - Amma", url: "https://www.amritapuri.org/", isActive: true },
      { title: "Sri Sri Ravi Shankar", url: "https://www.srisriravishankar.info/", isActive: false },
      { title: "Maharishi Mahesh Yogi", url: "https://www.maharishi.org/", isActive: true },
      { title: "Vedanta Cultural Foundation", url: "https://www.vedanta-edu.org/", isActive: true },
      { title: "Shri Ramana Maharshi", url: "https://www.sriramanamaharshi.org/", isActive: true },
      { title: "Amma Karunamayi", url: "https://www.karunamayi.org/", isActive: true },
      { title: "Divine Life Society", url: "https://www.dlshq.org/", isActive: true },
      { title: "Swami Krishnananda - Divine Life Society", url: "https://www.swami-krishnananda.org/", isActive: true , description: "This is the official website of Swami Krishnananda, and contains ebooks and articles on yoga, meditation, philosophy, scriptures, bhagavadgita, upanishads, spiritual practice, and poetry." },
      { title: "Sri Siddheswari Peetham", url: "https://www.siddheswaripeetham.com/", isActive: false },
      { title: "Swami Paramahansa Yogananda", url: "https://www.yogananda-srf.org/", isActive: true },
      { title: "Mataji Nirmala Devi", url: "https://www.adishakti.org/", isActive: true , description: "Adishakti.org is a living archive of the Divine Feminine, centered on the teachings and revelations of Shri Mataji Nirmala Devi. It explores the universal Spirit through Sahaja Yoga, Kundalini awakening, and the fulfillment of eschatological prophecies across Christianity, Hinduism, Islam, Taoism, and Judaism. The site documents mystical experiences, scriptural analysis, and the role of the Paraclete, Comforter, and Holy Spirit as feminine manifestations of divine truth. From the Devi Gita to the Gospel of Thomas, from Qiyamah to the Tao, this sanctuary invites seekers to rediscover the eternal Mother within and embrace the Tree of Life that lives in all." },
      { title: "Sant Shri Asaramji", url: "https://www.ashram.org/", isActive: true },
      { title: "Shree Maa - Temple of Devini Mother", url: "https://www.shreemaa.org/", isActive: true , description: "Discover the wisdom and teachings of Shree Maa, a spiritual guide dedicated to devotional worship, meditation, and selfless service. Explore mantras, books, and live events to deepen your spiritual journey." },
      { title: "Nisargadatta Maharaj", url: "https://www.nisargadatta.net/", isActive: true , description: "Dedicated to the teachings of Nisargadatta Maharaj and his talks on consciousness." },
      { title: "Siddha Peeth", url: "https://www.siddhayoga.org/", isActive: true , description: "Contemplate Gurumayi’s teachings from Mahashivaratri 2026" },
      { title: "Shankaracharya Swami Brahmanand Saraswati", url: "https://www.shrigurudevji.com/", isActive: false },
      { title: "Sri Sri Ma Anandamayi", url: "https://www.anandamayi.org/", isActive: true },
      { title: "Siddhar Sages From South India", url: "https://www.nandhi.com/", isActive: true , description: "Nandhiji Adhipen Bose" },
      { title: "Brahma Kumaris World Spiritual University", url: "https://www.bkwsu.com/", isActive: false },
      { title: "Gayatri Pariwar", url: "https://www.shriramsharma.com/", isActive: false },
      { title: "Kriyayoga Institute", url: "https://www.kriyayoga-yogisatyam.org/", isActive: true , description: "Discover Kriyayoga Meditation with Guruji Yogi Satyam at the Kriyayoga Ashram & Research Institute in Prayagraj. Experience daily group meditations, live Zoom sessions, and transformative spiritual programs designed to awaken your immortal nature and promote complete health, peace, and bliss." },
      { title: "Ved Mandir Ashram", url: "https://www.vedmandir.com/", isActive: true },
      { title: "Swami Narayan Tirtha", url: "https://www.swaminarayantirtha.org/", isActive: true , description: "Independent Distributor of Lifewave patches, light-infused water machine, and nutritional supplement that supports the patches." },
      { title: "Anandmurti Gurumaa", url: "https://www.gurumaa.com/", isActive: true , description: "Explore the inner world of peace, joy and bliss with powerful meditation, mantra chanting, soothing music, meditation retreats for healthy and conscious living." },
      { title: "Spiritual Research Foundation", url: "https://www.spiritualresearchfoundation.org/", isActive: true , description: "Leaders in spiritual research, bridging the known & unknown (spiritual) world. Dedicated to the spiritual progress of every person and society as a whole." },
      { title: "Osho International Foundation", url: "https://www.osho.com/", isActive: true , description: "Welcome to the world of OSHO – an opportunity to experience for yourself the essence of meditation. Read, watch, listen, and experience this revolutionary approach to discovering yourself." },
      { title: "Jiddu Krishnamurti - Official", url: "https://www.jkrishnamurti.org/", isActive: true },
    ],
  },
  {
    id: "vedic-intellectuals-western",
    title: "Vedic Intellectuals (Western)",
    links: [
      { title: "David Frawley - Vedic Pundit", url: "https://www.vedanet.com/", isActive: true , description: "Explore authentic Yoga, Ayurveda, and Vedic Astrology insights. Transform your life with our expert-guided courses and articles." },
      { title: "Stephen Knapp - Vaishnava Scholar", url: "https://www.stephen-knapp.com/", isActive: true , description: "This presents information on Stephen Knapp" },
      { title: "Micheal Cremo - Vaishnava Scholar", url: "https://www.mcremo.com/", isActive: true },
      { title: "Vyaas Houston - Sanskrit Guru", url: "https://www.americansanskrit.com/", isActive: true , description: "We offer every stage of Sanskrit Studies starting with a deep grounding in  the Sanskrit Alphabet provided in our breakthrough Weekend Sanskrit Level I  and/or our easy to follow Home Study programs . We make the study of  Sanskrit simple and enjoyable. All our programs are supported by free  consultation and online study groups." },
      { title: "Jeffrey Armstrong - Ayurvedic Astrologer", url: "https://www.jeffreyarmstrong.com/", isActive: true , description: "Seeking experienced guidance in relationships or major life decisions? Jeffrey Armstrong provides authoritative Vedic Astrology (Jyotish) consultations and an extensive online curriculum in Yoga Philosophy, with in-depth programs, classes, and retreats for dedicated yoga practitioners." },
      { title: "Dr. Frank Morales - Sri Dharma Pravartaka Acharya", url: "https://www.dharmacentral.com/", isActive: true },
      { title: "Gabriel Pradipaka - Sanskrit and Trika Pundit", url: "https://www.sanskrit-sanscrito.com.ar/", isActive: false , description: "This domain may be for sale!", tags: ["squatted"] },
      { title: "Freedom Cole - Astrology, Yoga and Ayurveda", url: "https://www.shrifreedom.com/", isActive: true },
      { title: "Gregorian Bivolaru - Romanian Yoga Guru", url: "https://www.sivasakti.com/", isActive: true },
      { title: "Vedavisharada Yogi Baba Prem Tom Beal", url: "https://www.floridavedicinstitute.com/", isActive: false },
      { title: "Shri Gurudev Mahendranath - Adi-Nath Sampradaya", url: "https://www.mahendranath.org/", isActive: true },
      { title: "Dandi Swami Jnaneshvara Bharati", url: "https://www.swamij.com/", isActive: false },
      { title: "Dennis Waite - Advaitha Teacher", url: "https://www.advaita.org.uk/", isActive: true },
      { title: "Aja Thomas - Atma Institute (Advaitha)", url: "https://www.atmainstitute.org/", isActive: false , description: "JABLAY123 adalah penyedia dan pilar dari permainan online, menjadi panutan banyak orang tua dengan memilih game beredukasi untuk anak-anak. JABLAY123 adalah pilihan tepat untuk meningkatkan IQ agar tidak seperti yang di belakang ku.", tags: ["gambling"] },
    ],
  },
  {
    id: "vedic-universities",
    title: "Vedic Universities",
    links: [
      { title: "Hindu University of America", url: "https://www.hindu-university.edu/", isActive: false },
      { title: "Maharshi University of Management", url: "https://www.mum.edu/", isActive: false },
      { title: "Florida Vedic College", url: "https://www.floridavediccollege.edu/", isActive: true , description: "XXX We are the first Vaishnava Vedic College in the USA, established in 1990 in Coral Springs, Florida.  We offer Associate" },
      { title: "European Academy of Vedic Sciences", url: "https://www.veda-academy.com/", isActive: true },
      { title: "Sri Aurobindo - University of Tomorrow", url: "https://www.theuniversityoftomorrow.org/", isActive: false , description: "Togel, togel singapore, togel hongkong, togel hari ini, data sgp, data hk, keluaran sgp, keluaran hk.", tags: ["gambling"] },
      { title: "Bhaktivedanta Academy", url: "https://www.vidyapitha.com/", isActive: true },
      { title: "Bhaktivedanta Vedic College USA", url: "https://www.bhaktivedantacollege.org/", isActive: false },
      { title: "Bhaktivedanta Vedic College Europe", url: "https://www.bhaktivedantacollege.com/", isActive: true , description: "AVAILABLE PROGRAMS & COURSES           Next 3 videos to watch:         Gardening the Hearts  Bhaktivedanta College, guided by Krishna-bhakti, provides education that nurtures students’ devotional, academic and" },
      { title: "Gurukulam - Institute of Vedanta", url: "https://www.arshavidya.org/", isActive: true },
      { title: "Institute of Vedanta in Brazil", url: "https://www.vidyamandir.org.br/", isActive: true , description: "O Centro de Estudos Vidya Mandir é uma instituição sem fins lucrativos que visa preservar a cultura e o conhecimento dos antigos Vedas e está focada no ensino de Vedanta e Sânscrito na língua portuguesa." },
      { title: "American College of Vedic Astrology", url: "https://www.vedicastrology.org/", isActive: true },
      { title: "Vedic Cultural Fellowship", url: "https://www.vedicworld.org/", isActive: true },
      { title: "SYDA - Indological Research Institute", url: "https://www.muktabodha.org/", isActive: false },
      { title: "Maharishi School of the Age of Enlightenment", url: "https://www.maharishischooliowa.org/", isActive: false },
      { title: "Rashtriya Sanskrit Sansthan", url: "https://www.sanskrit.nic.in/", isActive: true , description: "Central Sanskrit University, Established by an act of Parliament, it is a Premier University for promoting Sanskrit studies in India and abroad. It is the biggest Sanskrit University in the world today. Also, it is the only Multi-Campus Sanskrit University in India." },
      { title: "Deva Sanskriti Vishwa Vidhyalaya", url: "https://www.dsvv.org/", isActive: true , description: "The city of Delhi, the capital of India, is a fascinating place to explore. Discover the interesting architecture, the peaceful gardens and sample the food" },
    ],
  },
  {
    id: "vedic-townships",
    title: "Vedic Townships",
    links: [
      { title: "Maharishi Vedic City of Iowa", url: "https://www.maharishivediccity.net/", isActive: true },
      { title: "Universal City - Aurobindo's Vision", url: "https://www.auroville.org/", isActive: true },
      { title: "Spiritual Community of Hare Krishnas in Belgium", url: "https://www.radhadesh.com/", isActive: true },
    ],
  },
  {
    id: "sustaining-vedic-culture",
    title: "Sustaining Vedic Culture",
    links: [
      { title: "MahaShivaRatri: Night of Lord Shiva", url: "https://www.mahashivratri.org/", isActive: true , description: "Maha Shivratri - Shivratri is a famed Hindu festival commemorate in honour of Lord Shiva. Maha shivratri means the great night of lord shiva. Devotees prayers in front of Lord shiva inside the temple during maha shivratri. You can find here more information about shivratri, maha shivratri." },
      { title: "Holi: Festival of Colors", url: "https://www.holifestival.org/", isActive: true , description: "Holi 2025 - Holi is the festival of love or colors that signifies the victory of superior over immoral. Holi festival is commemorate on February end or starting March. You can find here more informative result about holi, holi day and more details on holifestival.org." },
      { title: "Diwali: Festival of Lights", url: "https://www.diwalifestival.org/", isActive: true , description: "Diwali (Deepawali) is the famous Hindu festival of light celebrated every year. This festival is one of India" },
      { title: "Bhai Dooj", url: "https://www.bhaidooj.org/", isActive: true , description: "Bhai Dooj - This Festival is celebrated by the Hindu’s on the last day of the Diwali festival. Bhai Dooj is also known as Bhau Beej, bhaiyya dooj. Bhaiya dooj is the way to communicating care and love to sibling by a sister." },
      { title: "Raksha Bandhan", url: "https://www.raksha-bandhan.com/", isActive: true , description: "Raksha Bandhan - Rakhi or raksha bandhan is a holy festival of india. Rakhi is a festival of faith and love between brother and sister, this page provides you the detailed information about rakhi, raksha bandhan and rakhi festival." },
      { title: "Durga Puja", url: "https://www.durga-puja.org/", isActive: true , description: "Durga Puja - Durga Puja is the major festival of Hinduism. This festival is also known as Durgotsava, is a popular festival across India. Festival particularly much more popular in the states of  West Bengal, Assam, Tripura, Bihar, Jharkhand, Odisha." },
      { title: "Karwa Chauth", url: "https://www.karwachauth.com/", isActive: false },
      { title: "Pongal: Harvest Festival of South India", url: "https://www.pongalfestival.org/", isActive: true , description: "Pongal - Pongal is the most popular festival of South India. This festival is also known as the harvest festival of India. Read more about Pongal, Pongal festival, the harvest festival of India and more on pongalfestival.org." },
      { title: "Baisakh: Harvest Festival of Punjab", url: "https://www.baisakhifestival.com/", isActive: true , description: "Baisakhi - Celebrate Baisakhi 2024 on April 14th, Wednesday. Vaisakhi holds tremendous significance for Sikhs.On Baisakhi Day, Guru Gobind Singh Ji organized Sikhs into Khalsa Panth. Read about Baisakhi festival." },
      { title: "Lohri: Festival to Worship Fire", url: "https://www.lohrifestival.org/", isActive: false , description: "Mawartoto adalah investor situs toto togel ternama di tahun ini, dengan bermacam macam promo yang di tawarkan dengan begitu banyak cuan dan keuntungan Top 1", tags: ["gambling"] },
      { title: "Onam: Homecoming of King Mahabali", url: "https://www.onamfestival.org/", isActive: true , description: "Onam festival - Onam is the biggest and popular festival of Indian State Kerala. This festival is celebrated as a harvest festival in Kerala. Read more about onam, onam festival and onam festival in India." },
      { title: "Teej: Dedicated to Shiva-Parvati", url: "https://www.teejfestival.org/", isActive: true , description: "Teej Festival - Details about teej festival, teej 2024, teej festival india, teej in india, teej celebrations, teej, teej fast, teej pooja process, teej customs, hartalika teej, kajli teej, haryali teej, kajrari teej, teej songs, teej fair, teej dance, teej gifts, teej recipes, teej messages, teej vrat katha, send teej gifts, teej cards, teej pictures, teej wallpapers." },
      { title: "Krishna Janmashtami", url: "https://www.krishnajanmashtami.com/", isActive: true , description: "Krishna Janmashtami - Krishna Janmashtami or Gokulashtami is the Hindu festival. The day specially dedicated to the Birth of Lord Krishna. Know more about Krishna Janmashtami, janmashtami, gokulashtami." },
      { title: "Information on Temples", url: "https://www.templenet.com/", isActive: true , description: "Templenet - The Ultimate Source of Information on Indian Temples features over 2000 temples with pointers to their architectural, cultural, religious, historical significance and  travel related information." },
      { title: "Devotional Songs", url: "https://www.devotionalsongs.com/", isActive: false },
      { title: "Puja", url: "https://www.archaka.com/", isActive: false },
      { title: "Bhajan Kirtan", url: "https://www.bhajans.org/", isActive: false },
      { title: "Temple Resources", url: "https://www.mandirnet.org/", isActive: false },
      { title: "Information on Jyotir Lingas", url: "https://www.jyotirlinga.com/", isActive: true , description: "This is Lord Shiva" },
      { title: "Worship Procedures by ISKCON", url: "https://www.deityworship.com/", isActive: true , description: "Sweetly Opulent Deity Worship Sweetly Opulent Deity Worship Deity Worshipaviator Deity Worship This is very important business, Deity worship. The more the Deity is decorated, the more your heart will be decorated with Krishna consciousness.\" (Srila Prabhupada Letter, October 7, 1974) \"The Lord is transcendental to our mundane senses. He cannot be seen with our" },
      { title: "Sri Vaishnava - Ramanujacharya", url: "https://www.ramanuja.org/", isActive: true },
      { title: "Krishna Science", url: "https://www.krishnascience.com/", isActive: false },
      { title: "Transcendental Meditation", url: "https://www.alltm.org/", isActive: false },
      { title: "Osho World", url: "https://www.oshoworld.com/", isActive: false },
      { title: "Paintings of Vedic Gods", url: "https://www.sanatansociety.com/", isActive: true , description: "Sanatan Society offers free wallpapers of hindu gods full-screen, yoga & meditation seminars, indian astrology, ayurvedic massage, home remedies, vegetarian recipes, online mantras,. and a lot more." },
      { title: "Martial Arts from Kerala", url: "https://www.kalarippayat.com/", isActive: true },
      { title: "Indian Dance and Music", url: "https://www.artindia.net/", isActive: true },
      { title: "Magazine For Indian Classical Music and Dance", url: "https://www.sruti.com/", isActive: false },
      { title: "Deepali Ravi - BharatNatyam", url: "https://www.nadanam.com/", isActive: true },
      { title: "Maitreya Buddha Project", url: "https://www.maitreyaproject.org/", isActive: false },
      { title: "Moscow Vedic Temple & Cultural Center", url: "https://www.moscowtemple.org/", isActive: false },
      { title: "Lord Subrahmanya Temples in Europe", url: "https://www.skandavale.org/", isActive: true },
    ],
  },
  {
    id: "communities",
    title: "Communities",
    links: [
      { title: "Sharing the Universal Dharma", url: "https://www.vedicfriends.org/", isActive: true },
      { title: "Soundarya Lahiri", url: "https://www.srimeru.org/", isActive: true , description: "Learn authentic traditional Srividya directly from Sri Guru Karunamaya. Learn to perform Sri Yantra puja and Meditation on Chakras." },
      { title: "Datta Yoga Center", url: "https://www.dycusa.org/", isActive: true },
      { title: "Art Of Living", url: "https://www.artofliving.org/", isActive: true , description: "Discover inner peace and personal transformation with The Art of Living, a global leader in meditation, breathwork, and wellness programs founded by Gurudev Sri Sri Ravi Shankar." },
      { title: "Students of Harish Johari", url: "https://www.sanatansociety.org/", isActive: true , description: "Sanatan Society offers free wallpapers of hindu gods full-screen, yoga & meditation seminars, indian astrology, ayurvedic massage, home remedies, vegetarian recipes, online mantras,. and a lot more." },
      { title: "Mata Amritanandamayi Devi", url: "https://www.amma.org/", isActive: true , description: "Learn about Amma’s life, work, and wisdom. Get latest news from Amma&#039;s humanitarian initiatives and more. Find groups, centers, and events near you." },
      { title: "Shri Satya Sai Baba", url: "https://www.sathyasai.org/", isActive: true },
      { title: "Transcendental Meditation", url: "https://www.tm.org/", isActive: true , description: "The TM course offers a personalized journey to inner peace, clarity, & wellness. It has wide-ranging benefits for all areas of life, find out more here." },
      { title: "Divya Yoga", url: "https://www.divyayoga.com/", isActive: true , description: "Scroll Down Who We Are Divya Yog Mandir Trust was founded by Swami Ramdev Ji and Acharya Balkrishna Ji, with the assistance of Pujya Swami&hellip;" },
      { title: "Yogacharya B.K.S. Iyengar", url: "https://www.bksiyengar.com/", isActive: true , description: "Yogacharya B.K.S. Iyengar with his intellectual and spiritual practices has masterminded the techniques which can be used by all practitioners of yoga." },
      { title: "Bikram Yoga", url: "https://www.bikramyoga.com/", isActive: true , description: "26 Asanas | 90 Minutes" },
      { title: "Sahaja Yoga", url: "https://www.sahajayoga.org/", isActive: true },
      { title: "Shakti Sadhana", url: "https://www.shaktisadhana.org/", isActive: false },
      { title: "Bhagwan Swaminarayan - BAPS", url: "https://www.swaminarayan.org/", isActive: true , description: "BAPS Swaminarayan Sanstha" },
      { title: "ISKCON", url: "https://www.iskcon.org/", isActive: true },
      { title: "Spiritual Teachings of Ancient India", url: "https://www.arshabodha.org/", isActive: true , description: "Welcome to Arsha Bodha Center A traditional ashram founded by Swami Tadatmananda, a disciple of Pujya Swami Dayananda, to teach the wisdom (bodha) of the sages of ancient India (arsha).   Announcements Online Course in Advaita Vedanta, Meditation & Sanskrit Conducted by Swami Tadatmananda and Vasanthi ji Swami Tadatmananda is planning to conduct an intensive [&hellip;]" },
      { title: "Upliftment of Brahmin Community", url: "https://www.dhanwantri.org/", isActive: true },
      { title: "Classical Yoga Hindu Academy", url: "https://www.classicalyoga.org/", isActive: true , description: "Authentic Hindu/Yoga teachings and practices: Karma Yoga; Bhakti Yoga; Hatha Yoga; Raja Yoga/Kundalini Yoga and Jnana Yoga" },
      { title: "Ashram - Path of Om Yoga meditation", url: "https://www.atmajyoti.org/", isActive: false },
      { title: "International Nath Order", url: "https://www.nathorder.org/", isActive: true },
      { title: "Hare Krishna Center For Vedic Studies", url: "https://www.gauranga.org/", isActive: true },
      { title: "International Gita Society", url: "https://www.gita-society.com/", isActive: true , description: "Bhagavad-Gita Teachings in 27Int’l,Arabic&IndianLanguages, Gita Audios-videos, books. GitaForChildren&Inmates, FREE Download of Vedic scriptures & more" },
      { title: "Maharishi Vedic Community USA", url: "https://www.vedic-community.org/", isActive: false },
      { title: "Mandala Yoga Ashram - UK", url: "https://www.mandalayoga.net/", isActive: true , description: "Mandala Yoga Ashram UK is an authentic yoga ashram and internationally renowned centre of yoga studies. Our beautiful ashram in Wales offers residential yoga retreats and online courses in yoga, advaita and tantra. If you're looking for yoga retreat centre in the UK, we have all the OM's you need." },
      { title: "All World Gayatri Pariwar", url: "https://www.awgp.org/", isActive: true , description: "Explore AWGP.org, the official website of All World Gayatri Pariwar (AWGP)—a global spiritual and social organization founded by Pandit Shriram Sharma Acharya. Discover initiatives for moral upliftment, social reform, environmental consciousness, scientific spirituality, and holistic development. Access transformative literature, participate in spiritual practices like Gayatri Yagna and meditation, and join efforts to create a harmonious society. Stay updated with events, campaigns, and resources that inspire self-transformation and societal progress. Visit AWGP.org to connect with a community dedicated to universal peace and prosperity." },
      { title: "Friends of OSHO", url: "https://www.sannyas.net/", isActive: true , description: "A 65,000+ page Wiki about Osho (Bhagwan Shree Rajneesh) and Sannyas" },
      { title: "Krishnamurti Information Network", url: "https://www.kinfonet.org/", isActive: true },
    ],
  },
  {
    id: "political-ideologues",
    title: "Political Ideologues",
    links: [
      { title: "Mahatma Gandhi - Life, Work & Philosophy", url: "https://www.mkgandhi.org/", isActive: true , description: "World" },
      { title: "Mahatma Gandhi - A 'Voilent' Pacifist", url: "https://www.gandhibapu.com/", isActive: true , description: "Gandhibapu.com a website Dedicated to Mahatma Gandhi the father of our Nation Bharat (India)." },
      { title: "Vinayak Damodar Savarkar - 'Hindutva' Ideology", url: "https://www.savarkar.org/", isActive: true , description: "Vinayak Damodar Savarkar, commonly known as Swatantryaveer Savarkar was a fearless freedom fighter, social reformer, writer, dramatist, poet, historian, political leader and philosopher." },
      { title: "Shri Golwalkar - Ex RSS Chief", url: "https://www.golwalkarguruji.org/", isActive: true , description: "Shree Guruji" },
    ],
  },
  {
    id: "organizations",
    title: "Organizations",
    links: [
      { title: "Rashtriya Swayamsevak Sangh", url: "https://www.rss.org/", isActive: true , description: "Rashtriya Swayamsevak Sangh" },
      { title: "Vishwa Hindu Parishad", url: "https://www.vhp.org/", isActive: true },
      { title: "Vishwa Hindu Parishad America", url: "https://www.vhp-america.org/", isActive: true , description: "Premium Membership Associate/Free Membership Donate VHPA is the oldest and one of the largest Hindu organizations in the US. Our foundational principles are :- 01. Vasudhaiva Kutumbakam :- Entire universe is one family. 02. Sarve Bhavantu Sukhinah :- May all be happy. 03. Ekam Sat, Viprah Bhudha Vadanti :- Truth is one; Sages speak of [&hellip;]" },
      { title: "Bajrang Dal", url: "https://www.hinduunity.com/", isActive: true , description: "Shop a wide selection of domains at HugeDomains.com. Find the right domain name today." },
      { title: "Ekal Vidhyalaya", url: "https://www.ekalindia.org/", isActive: true , description: "Sempatigame merupakan daftar situs main game makin asik dan mudah dengan sistem praktik QRIS instan. Tanpa proses lama, tanpa tunggu antrian, langsung masuk hitungan detik." },
      { title: "Hindu Human Rights", url: "https://www.hinduhumanrights.org/", isActive: true , description: "Enlightening the world" },
      { title: "Hindu Swayamsevak Sangh", url: "https://www.hssworld.org/", isActive: true , description: "Main Page of Hindu Swayamsevak Sangh" },
      { title: "Bharatiya Janata Party", url: "https://www.bjp.org/", isActive: true , description: "Bharatiya Janata Party is the largest political party" },
      { title: "American Hindu Voice", url: "https://www.hinduamericanfoundation.org/", isActive: true , description: "The Hindu American Foundation (HAF) is a non-profit advocacy organization for the Hindu American community. HAF&#039;s work impacts a range of issues: from the portrayal of Hinduism in K-12 textbooks to civil and human rights to addressing contemporary problems, such as environmental protection and inter-religious conflict, by applying Hindu philosophy." },
      { title: "Hindu Forum of Britain", url: "https://www.hinduforum.org/", isActive: true },
      { title: "Monthly Magazine in UK", url: "https://www.thehinduvoice.com/", isActive: false },
      { title: "Activities For Kids", url: "https://www.balagokulam.org/", isActive: true },
      { title: "Friends Of India Society International", url: "https://www.fisiusa.org/", isActive: true },
      { title: "Swadeshi Jagran Manch", url: "https://www.swadeshi.org/", isActive: false },
      { title: "Kashmiri Hindu Liberation Army", url: "https://www.hindurashtra.org/", isActive: true , description: "Welcome To HinduRashtra.Org" },
      { title: "Sri Jagannath Center - Jyotish", url: "https://www.srijagannath.org/", isActive: false },
      { title: "Collective Voice of Hindu Society", url: "https://www.acharyasabha.org/", isActive: true , description: "Hindu Dharma Acharya Sabha  - Home" },
      { title: "Hindu Students Council", url: "https://www.hscnet.org/", isActive: true },
      { title: "India Development and Relief Fund", url: "https://www.idrf.org/", isActive: true , description: "IDRF is a trusted charity in USA, supporting women empowerment, health, education and skill development for under privileged sections in India. IDRF is a charity which aims to empower marginalized people with skills, services and infrastructure grounded in sustainable development in India." },
      { title: "Infinity Foundation", url: "https://www.infinityfoundation.com/", isActive: true , description: "WELCOME TO INFINITY FOUNDATION ​​ Infinity Foundation is a non-profit organization based in Princeton (USA), focused on research and education. It specializes in the field of civilization studies applying the  Continue Reading &rarr;" },
      { title: "Youth Activities", url: "https://www.hinduyuva.org/", isActive: true , description: "Hindu YUVA aims to provide a platform to preserve, practice, promote, and protect Hindu Dharma by bringing together Hindu youth on college campuses across North America." },
      { title: "Serving Hindus of North America", url: "https://www.hinduamerica.com/", isActive: false },
      { title: "Let India Develop", url: "https://www.letindiadevelop.org/", isActive: true },
      { title: "Hindu Heritage Endowment", url: "https://www.hheonline.org/", isActive: true , description: "Hindu Heritage Endowment is a non-profit trust serving Hindu institutions globally by supporting their goals of higher education, health care, children" },
      { title: "Organization Promoting Sanskrit", url: "https://www.samskritabharati.org/", isActive: true , description: "Discover the global presence of Samskrita Bharati, a non-profit organization dedicated to promoting Sanskrit as a spoken language. Connect with communities worldwide and access a wealth of knowledge. Join a local class or start a new chapter today!" },
      { title: "International Forum for India's Heritage", url: "https://www.jaia-bharati.org/", isActive: false },
    ],
  },
  {
    id: "news-magazines",
    title: "News & Magazines",
    links: [
      { title: "Daily Pioneer", url: "https://www.dailypioneer.com/", isActive: true , description: "Created with Daily Pioneer" },
      { title: "National Daily From Chennai", url: "https://www.newstodaynet.com/", isActive: true , description: "Congress Seat Demands Trigger Fresh Strain in DMK Alliance Talks NT BureauMarch 21, 20260 Ramzan celebrated across the globe, Governor, Stalin extended greetings NT BureauMarch 21, 20260 Air India cancels 2,500 flights to West Asia; CEO says airline operating at 30% capacity Defeating DMK is the Goal: TTV Dhinakaran After Meeting Amit Shah NT BureauMarch" },
      { title: "Collection of Daily News", url: "https://www.sarvesamachar.com/", isActive: false },
      { title: "RSS portal", url: "https://www.organiser.org/", isActive: true , description: "Organiser is one of the oldest and most widely circulated nationalist English weekly of Bharat, spreading cultural & nationalist views, beyond news." },
      { title: "Hindu News from Kerala", url: "https://www.haindavakeralam.org/", isActive: false },
      { title: "News Portal", url: "https://www.hinduvoice.net/", isActive: true },
      { title: "News Portal (Jagruti)", url: "https://www.hindujagruti.org/", isActive: true },
      { title: "Hindu Universe", url: "https://www.hindunet.com/", isActive: false },
      { title: "Links to Hindu Activities", url: "https://www.hindulinks.org/", isActive: false },
      { title: "Public Opinion Forum", url: "https://www.vigilonline.com/", isActive: true , description: "Easy, affordable options for you to obtain the domain you want. Safe and secure shopping." },
      { title: "Hindu Vivek Kendra", url: "https://www.hvk.org/", isActive: true },
      { title: "Vaishnava News Network", url: "https://www.vnn.org/", isActive: false },
      { title: "Hinduism Today", url: "https://www.hinduismtoday.com/", isActive: true , description: "AboutHinduism Today® Magazine is a nonprofit educational activity of Himalayan Academy with the following purposes: 1. To fosterHindu solidarity as a" },
      { title: "Quarterly by Maharishi Vedic Edu", url: "https://www.enlightenmenttoday.com/", isActive: true },
      { title: "News From Indian Sub-Continent", url: "https://indiaview.wordpress.com/", isActive: true , description: "News from Indian Sub-Continent" },
      { title: "Magazine of Gayatri Pariwar", url: "https://www.akhandjyoti.org/", isActive: true , description: "Akhand Jyoti is the largest NGO & charitable non profit organization in Bihar, India working towards eliminating curable blindness & empowering rural girls." },
    ],
  },
  {
    id: "opinions-articles",
    title: "Opinions & Articles",
    links: [
      { title: "Voice of Dharma", url: "https://www.voiceofdharma.org/", isActive: true },
      { title: "Quotes on Hinduism", url: "https://www.hinduwisdom.info/", isActive: true },
      { title: "Pride of Indian Culture", url: "https://www.indpride.com/", isActive: false },
      { title: "Archeological Evidence", url: "https://www.archaeologyonline.net/", isActive: false },
      { title: "Indian Science and Technology", url: "https://www.indianscience.org/", isActive: true },
      { title: "Indology - Gateway to Ancient India", url: "https://www.gosai.com/", isActive: true },
      { title: "The Hindu Renaissance", url: "https://www.hindurenaissance.com/", isActive: false },
      { title: "Francois Gautier - Journalist", url: "https://www.francoisgautier.com/", isActive: true },
      { title: "Hindu Identity of India", url: "https://vivekajyoti.blogspot.com/", isActive: true },
      { title: "Resume of Hindu Thought", url: "https://hinduthinktank.blogspot.com/", isActive: true },
      { title: "Rajeev Srinivasan - Journalist", url: "https://rajeev2004.blogspot.com/", isActive: true , description: "A Hindu Nationalist Perspective" },
      { title: "Devoted to 'Bharat' and 'Dharma'", url: "https://www.satyameva-jayate.org/", isActive: true , description: "Dedicated to Bharat and Dharma" },
      { title: "Indic Studies Foundation", url: "https://www.indicstudies.us/", isActive: false , description: "This domain may be for sale!", tags: ["squatted"] },
      { title: "The Vedic Foundation", url: "https://www.thevedicfoundation.org/", isActive: false },
      { title: "Preserve and Revive Hinduism", url: "https://www.hindusarise.com/", isActive: false , description: "This domain may be for sale!", tags: ["squatted"] },
      { title: "Vedic Astronomy Enthusiast", url: "https://www.vedicastronomy.net/", isActive: true },
      { title: "Dedicated To Bharat", url: "https://www.esamskriti.com/", isActive: false },
      { title: "Indian Culture and History", url: "https://azygos.sulekha.com/", isActive: true , description: "Get your job done on Sulekha. Book a pest control service, hire a driver, find suitable packers and movers, sign up a corporate event organizer, compare and hire a wedding caterer or buy a home.  Do this and much more with Sulekha. Tell us and relax!" },
      { title: "Uniting Hindu Society Worldwide", url: "https://www.sanghparivar.org/", isActive: true },
      { title: "Indian Leaders' Speeches", url: "https://www.theuniversalwisdom.org/", isActive: false , description: "Game Judi Online, Slot Gacor, Live Casino Dan Game Lainnya", tags: ["gambling"] },
      { title: "Sangh Parivar Insider", url: "https://sangh.wordpress.com/", isActive: true , description: "A swayamsevaks\&#039;s musing on Sangh Parivar" },
      { title: "Secular India", url: "https://indiasecular.wordpress.com/", isActive: true , description: "Secular & Democratic India" },
      { title: "Faith, Culture and Politics", url: "https://indowave.tripod.com/", isActive: true },
      { title: "News Analysis India", url: "https://www.newsanalysisindia.com/", isActive: true , description: "The news you need to know, explained" },
      { title: "India Awakening", url: "https://ariseindiaarise.blogspot.com/", isActive: true },
      { title: "Teesta Setalvad - Anti-India Activist", url: "https://teesta.blogspot.com/", isActive: false },
      { title: "Communal Politics of Indian Congress", url: "https://truecongresspolitics.wordpress.com/", isActive: true , description: "True Indian congress dirty communal politics&#039;s Weblog" },
      { title: "Nehru Family", url: "https://www.nehrufamily.com/", isActive: true },
      { title: "Gurumurthy - CA, Journalist", url: "https://www.gurumurthy.net/", isActive: true },
      { title: "Foundation Against Continuing Terrorism", url: "https://factusa.blogspot.com/", isActive: false },
      { title: "Basic Information on Indian Culture", url: "https://www.bharatwisdom.com/", isActive: true , description: "Explore the Avada Online School Prebuilt Website, crafted for modern e-learning. Showcase courses, engage students, and optimize the user experience." },
      { title: "Current Affairs", url: "https://www.sandeepweb.com/", isActive: true , description: "SandeepWeb is a blog for research and reviews of different products that will help users to decide if the product is best for them or not." },
      { title: "Voice of Free Indian", url: "https://www.geocities.com/bharatvarsha1947/", isActive: true , description: "Latest news coverage, email, free stock quotes, live scores and video are just the beginning. Discover more every day at Yahoo!" },
      { title: "Indian Nation and its Heritage", url: "https://www.akhandbharat.org/", isActive: false },
    ],
  },
  {
    id: "threats-challenges",
    title: "Threats & Challenges",
    links: [
      { title: "Crusade Watch", url: "https://www.crusadewatch.org/", isActive: false },
      { title: "Christian Missionary Aggression", url: "https://www.christianaggression.org/", isActive: false },
      { title: "History of Christianity in India", url: "https://www.hamsa.org/", isActive: true },
      { title: "Missionary Agenda", url: "https://conversionagenda.blogspot.com/", isActive: true },
      { title: "Christian Atrocities and Inquisitions", url: "https://www.burningcross.net/", isActive: false },
      { title: "Islamic Terrorism in India", url: "https://islamicterrorism.wordpress.com/", isActive: true , description: "Most Muslims are not terrorists, but most terrorists are Muslims" },
      { title: "Human Rights Congress For Bangladesh Minorities", url: "https://www.hrcbm.org/", isActive: true , description: "HRCBM is a Human Rights and Humanitarian Organization working to procure justice and uphold rights and dignities of Bangladesh Minorities." },
      { title: "Fate Of Kashmir Hindus", url: "https://www.panunkashmir.org/", isActive: true },
      { title: "Kashmir - Paradise Turned Into Hell", url: "https://www.kashmir-information.com/", isActive: true },
      { title: "Kashmiri Hindus 'Exiled' In Home Country", url: "https://www.kashmiri-pandit.org/", isActive: true },
      { title: "Bengal Partition", url: "https://www.bengalvoice.com/", isActive: false },
      { title: "Addressing Naxalite Menace", url: "https://naxalwatch.blogspot.com/", isActive: false },
      { title: "Communist Party Marxist Terror", url: "https://cpmterror.blogspot.com/", isActive: true },
      { title: "Communism Watch", url: "https://communismwatch.blogspot.com/", isActive: true },
      { title: "Voice of Nationalist Hindus", url: "https://pseudosecularism.blogspot.com/", isActive: true },
      { title: "Indian media accountability", url: "https://truthprevails.wordpress.com/", isActive: true , description: "Rated R for material offensive to Indian pseudo-liberals" },
      { title: "Chindu Newspaper", url: "https://cbcnn.blogspot.com/", isActive: true , description: "Chennai-Based Chinese National Newspaper (CBCNN)" },
      { title: "South Asian Bleeding Hearts Association", url: "https://www.sabha.info/", isActive: true },
      { title: "Sankaracharya Arrest Episode", url: "https://sankaracharyaarticles.blogspot.com/", isActive: false },
      { title: "Kanchi Shankaracharya - Authentic Info", url: "https://www.kanchi-sathya.org/", isActive: false },
      { title: "Govt Taking Over Temples", url: "https://www.savetemples.org/", isActive: true , description: "SaveTemples.org! Mission to Protect and Preserve Hinduism and Hindu Temples Worldwide. | A project of Global Hindu Heritage Foundation [GHHF] USA" },
      { title: "Global Hindu Heritage Foundation", url: "https://www.preservehinduism.org/", isActive: true , description: "SaveTemples.org! Mission to Protect and Preserve Hinduism and Hindu Temples Worldwide. | A project of Global Hindu Heritage Foundation [GHHF] USA" },
      { title: "Save Rama Setu", url: "https://saveramasetu.blogspot.com/", isActive: true , description: "Obat Wasir Ambeien Herbal Ambeclear terbuat 100% dari bahan alami terbukti manjur mengobati wasir tanpa operasi call 082 135 393 111" },
      { title: "Rama's Bridge", url: "https://www.bridgeofram.com/", isActive: false },
      { title: "Rama Setu Information", url: "https://www.ramsethu.org/", isActive: true , description: "Menjaga Warisan, Menghubungkan Sejarah dan Spiritualitas." },
      { title: "Online Hindu Holocaust Memorial Museum", url: "https://www.hinduholocaust.com/", isActive: false },
      { title: "Holocaust Down the Timeline", url: "https://www.geocities.com/hindoo_humanist/", isActive: true , description: "Latest news coverage, email, free stock quotes, live scores and video are just the beginning. Discover more every day at Yahoo!" },
    ],
  },
];
