export interface ResourceLink {
  title: string;
  url: string;
  description?: string;
}

export interface ResourceCategory {
  id: string;
  title: string;
  links: ResourceLink[];
}

export const resourceData: ResourceCategory[] = [
  {
    id: "vedic-wisdom",
    title: "Vedic Wisdom",
    links: [
      { title: "Bhakti Vedanta", url: "http://www.vedabase.org/", description: "A comprehensive digital library for the works of A.C. Bhaktivedanta Swami Prabhupada and the Gaudiya Vaishnava tradition." },
      { title: "Maharishi University of Management", url: "http://www.mum.edu/vedicreserve/", description: "A repository of the extensive Vedic Literature collection preserved by Maharishi Mahesh Yogi's organization." },
      { title: "Ramayana - Critical Edition", url: "http://www.valmikiramayan.net/", description: "A detailed, verse-by-verse presentation of the Valmiki Ramayana, including Sanskrit text and English translations." },
      { title: "Bhagavad Gita - Vaishnava Sampradaya", url: "http://www.bhagavad-gita.org/", description: "A scholarly presentation of the Bhagavad Gita according to the four authentic Vaishnava successions." },
      { title: "Swami Prabhupada - Bhagavad Gita As It Is", url: "http://www.asitis.com/", description: "The world's most widely read edition of the Gita, with original Sanskrit, word-for-word meanings, and elaborate purports." },
      { title: "Mahabharat & Related Stories", url: "http://www.mahabharataonline.com/", description: "A digital hub for the Mahabharata epic, offering stories, character details, and thematic analysis." },
      { title: "Mahabharata Resources", url: "http://www.mahabharata-resources.org/", description: "A collaborative resource for scholars and students of the Mahabharata and related Puranic literature." },
      { title: "Wisdom of Tantrik Tradition", url: "http://www.shivashakti.com/", description: "Exploration of the Shiva-Shakti traditions, including Tantra, Yoga, and Kashmiri Shaivism." },
      { title: "Vatsayana - Kama Sutra", url: "http://www.kamasutra-sex.org/", description: "An authentic translation of the ancient Sanskrit text on human behavior and ethics." },
      { title: "Sanskrit Documents' Collection", url: "http://www.sanskritdocuments.org/", description: "A massive archive of Sanskrit texts in various formats (ITRANS, PDF, Devanagari) across all branches of literature." },
      { title: "Vedic Documents - Stiehl's Collection", url: "http://www.sanskritweb.net/", description: "High-quality PDF editions of major Vedic Samhitas and Brahmanas, typeset with accentuation." },
      { title: "Sanskrit Texts and Stotras", url: "http://sanskrit.safire.com/", description: "A curated collection of popular stotras and technical Sanskrit treatises." },
      { title: "English Translations of Vedic Scriptures", url: "http://www.hinduwebsite.com/", description: "Extensive translations and articles on Hinduism, Buddhism, Jainism, and Sikhism." },
      { title: "Vedic Sacred Texts", url: "http://www.sacred-texts.com/hin/", description: "A global archive of world religion and mythology texts, with a strong focus on Hindu scriptures." },
      { title: "Online Spiritual Library", url: "http://www.celextel.org/", description: "A digital library focusing on the Upanishads and works of Adi Shankaracharya." },
      { title: "Vedas and Puranas In Hindi", url: "http://www.vedpuran.com/", description: "Accessible Hindi translations of the four Vedas and major Maha-Puranas." },
      { title: "Sanskrit English online translation", url: "http://www.spokensanskrit.de/", description: "A powerful, bidirectional Sanskrit-English dictionary and grammar reference." },
      { title: "Shri Madhvacharya's Doctrine", url: "http://www.dvaita.org/", description: "The primary resource for Dvaita Vedanta philosophy as propounded by Sri Madhvacharya." },
      { title: "Introduction to Advaita Vedanta", url: "http://www.advaita-vedanta.org/", description: "Scholarly introductions and discussions on the non-dualistic philosophy of Advaita." },
      { title: "Gateway To Advaita Vedanta", url: "http://www.shankaracharya.org/", description: "Dedicated to the life and works of Adi Shankaracharya, the primary teacher of Advaita." },
      { title: "Sri Sathya Sai Veda Pratishtan", url: "http://www.vedamu.org/", description: "An educational portal dedicated to Vedic chanting and the preservation of Vedic knowledge." },
      { title: "Sri Aurobindo Kapali Sastry Institute", url: "http://www.vedah.com/", description: "Research and publications on the deeper esoteric meaning of the Vedas based on Sri Aurobindo's vision." },
      { title: "Satguru Sivaya Subramuniyaswami", url: "http://www.himalayanacademy.com/", description: "Resources from the Kauai Hindu Monastery, including Hinduism Today magazine and educational books." },
      { title: "Understanding Vedic Culture", url: "http://www.hinduism.co.za/", description: "A thematic exploration of Vedic culture and philosophy for modern audiences." },
      { title: "Sanatan Dharma Information", url: "http://www.urday.com/", description: "Introductory information on Sanatana Dharma protocols, festivals, and philosophies." },
      { title: "The Hindu Encyclopedia", url: "http://www.hindupedia.com/", description: "A community-driven wiki for comprehensive information on all aspects of Hinduism." },
      { title: "A Hindu Blog", url: "http://www.hindu-blog.com/", description: "Daily updates on Hindu news, festivals, and spiritual insights." },
      { title: "Buddha Dharma Education Association", url: "http://www.buddhanet.net/", description: "Global Buddhist network providing educational resources and meditation guides." },
      { title: "Jainism Global Resource Center", url: "http://www.jainworld.com/", description: "Comprehensive library for Jain philosophy, history, and practice." },
    ],
  },
  {
    id: "international-vedic",
    title: "International Vedic Culture",
    links: [
      { title: "Russian Vedic Culture", url: "http://www.gauranga.org/vedic.htm" },
      { title: "World Vedic Influence", url: "http://personalpages.tds.net/~theseeker/Ts.htm" },
      { title: "Abraham - The Brahmin", url: "http://www.mondovista.com/abraham.html" },
      { title: "Noah - From Vedic Flood Stories", url: "http://www.mondovista.com/noah.story.html" },
      { title: "Vedic Civilization Spread", url: "http://www.vedicempire.com/" },
      { title: "Hare Krishna Spiritual Resource Network", url: "http://www.salagram.net/" },
    ],
  },
  {
    id: "vedic-intellectuals-indian",
    title: "Vedic Intellectuals (Indian)",
    links: [
      { title: "Vivekananda's Views", url: "http://www.vivekanandagospel.org/" },
      { title: "Works of Ramakrishna and Vivekananda", url: "http://www.ramakrishnavivekananda.info/" },
      { title: "Sri Aurobindo Ashram", url: "http://www.sriaurobindoashram.info/" },
      { title: "Kanchi Kamakoti Peetham - Official", url: "http://www.kamakoti.org/" },
      { title: "Mata Amritanandamayi Devi - Amma", url: "http://www.amritapuri.org/" },
      { title: "Sri Sri Ravi Shankar", url: "http://www.srisriravishankar.info/" },
      { title: "Maharishi Mahesh Yogi", url: "http://www.maharishi.org/" },
      { title: "Vedanta Cultural Foundation", url: "http://www.vedanta-edu.org/" },
      { title: "Shri Ramana Maharshi", url: "http://www.sriramanamaharshi.org/" },
      { title: "Amma Karunamayi", url: "http://www.karunamayi.org/" },
      { title: "Divine Life Society", url: "http://www.dlshq.org/" },
      { title: "Swami Krishnananda - Divine Life Society", url: "http://www.swami-krishnananda.org/" },
      { title: "Sri Siddheswari Peetham", url: "http://www.siddheswaripeetham.com/" },
      { title: "Swami Paramahansa Yogananda", url: "http://www.yogananda-srf.org/" },
      { title: "Mataji Nirmala Devi", url: "http://www.adishakti.org/" },
      { title: "Sant Shri Asaramji", url: "http://www.ashram.org/" },
      { title: "Shree Maa - Temple of Devini Mother", url: "http://www.shreemaa.org/" },
      { title: "Nisargadatta Maharaj", url: "http://www.nisargadatta.net/" },
      { title: "Siddha Peeth", url: "http://www.siddhayoga.org/" },
      { title: "Shankaracharya Swami Brahmanand Saraswati", url: "http://www.shrigurudevji.com/" },
      { title: "Sri Sri Ma Anandamayi", url: "http://www.anandamayi.org/" },
      { title: "Siddhar Sages From South India", url: "http://www.nandhi.com/" },
      { title: "Brahma Kumaris World Spiritual University", url: "http://www.bkwsu.com/" },
      { title: "Gayatri Pariwar", url: "http://www.shriramsharma.com/" },
      { title: "Kriyayoga Institute", url: "http://www.kriyayoga-yogisatyam.org/" },
      { title: "Ved Mandir Ashram", url: "http://www.vedmandir.com/" },
      { title: "Swami Narayan Tirtha", url: "http://www.swaminarayantirtha.org/" },
      { title: "Anandmurti Gurumaa", url: "http://www.gurumaa.com/" },
      { title: "Spiritual Research Foundation", url: "http://www.spiritualresearchfoundation.org/" },
      { title: "Osho International Foundation", url: "http://www.osho.com/" },
      { title: "Jiddu Krishnamurti - Official", url: "http://www.jkrishnamurti.org/" },
    ],
  },
  {
    id: "vedic-intellectuals-western",
    title: "Vedic Intellectuals (Western)",
    links: [
      { title: "David Frawley - Vedic Pundit", url: "http://www.vedanet.com/" },
      { title: "Stephen Knapp - Vaishnava Scholar", url: "http://www.stephen-knapp.com/" },
      { title: "Micheal Cremo - Vaishnava Scholar", url: "http://www.mcremo.com/" },
      { title: "Vyaas Houston - Sanskrit Guru", url: "http://www.americansanskrit.com/" },
      { title: "Jeffrey Armstrong - Ayurvedic Astrologer", url: "http://www.jeffreyarmstrong.com/" },
      { title: "Dr. Frank Morales - Sri Dharma Pravartaka Acharya", url: "http://www.dharmacentral.com/" },
      { title: "Gabriel Pradipaka - Sanskrit and Trika Pundit", url: "http://www.sanskrit-sanscrito.com.ar/" },
      { title: "Freedom Cole - Astrology, Yoga and Ayurveda", url: "http://www.shrifreedom.com/" },
      { title: "Gregorian Bivolaru - Romanian Yoga Guru", url: "http://www.sivasakti.com/" },
      { title: "Vedavisharada Yogi Baba Prem Tom Beal", url: "http://www.floridavedicinstitute.com/" },
      { title: "Shri Gurudev Mahendranath - Adi-Nath Sampradaya", url: "http://www.mahendranath.org/" },
      { title: "Dandi Swami Jnaneshvara Bharati", url: "http://www.swamij.com/" },
      { title: "Dennis Waite - Advaitha Teacher", url: "http://www.advaita.org.uk/" },
      { title: "Aja Thomas - Atma Institute (Advaitha)", url: "http://www.atmainstitute.org/" },
    ],
  },
  {
    id: "vedic-universities",
    title: "Vedic Universities",
    links: [
      { title: "Hindu University of America", url: "http://www.hindu-university.edu/" },
      { title: "Maharshi University of Management", url: "http://www.mum.edu/" },
      { title: "Florida Vedic College", url: "http://www.floridavediccollege.edu/" },
      { title: "European Academy of Vedic Sciences", url: "http://www.veda-academy.com/" },
      { title: "Sri Aurobindo - University of Tomorrow", url: "http://www.theuniversityoftomorrow.org/" },
      { title: "Bhaktivedanta Academy", url: "http://www.vidyapitha.com/" },
      { title: "Bhaktivedanta Vedic College USA", url: "http://www.bhaktivedantacollege.org/" },
      { title: "Bhaktivedanta Vedic College Europe", url: "http://www.bhaktivedantacollege.com/" },
      { title: "Gurukulam - Institute of Vedanta", url: "http://www.arshavidya.org/" },
      { title: "Institute of Vedanta in Brazil", url: "http://www.vidyamandir.org.br/" },
      { title: "American College of Vedic Astrology", url: "http://www.vedicastrology.org/" },
      { title: "Vedic Cultural Fellowship", url: "http://www.vedicworld.org/" },
      { title: "SYDA - Indological Research Institute", url: "http://www.muktabodha.org/" },
      { title: "Maharishi School of the Age of Enlightenment", url: "http://www.maharishischooliowa.org/" },
      { title: "Rashtriya Sanskrit Sansthan", url: "http://www.sanskrit.nic.in/" },
      { title: "Deva Sanskriti Vishwa Vidhyalaya", url: "http://www.dsvv.org/" },
    ],
  },
  {
    id: "vedic-townships",
    title: "Vedic Townships",
    links: [
      { title: "Maharishi Vedic City of Iowa", url: "http://www.maharishivediccity.net/" },
      { title: "Universal City - Aurobindo's Vision", url: "http://www.auroville.org/" },
      { title: "Spiritual Community of Hare Krishnas in Belgium", url: "http://www.radhadesh.com/" },
    ],
  },
  {
    id: "sustaining-vedic-culture",
    title: "Sustaining Vedic Culture",
    links: [
      { title: "MahaShivaRatri: Night of Lord Shiva", url: "http://www.mahashivratri.org/" },
      { title: "Holi: Festival of Colors", url: "http://www.holifestival.org/" },
      { title: "Diwali: Festival of Lights", url: "http://www.diwalifestival.org/" },
      { title: "Bhai Dooj", url: "http://www.bhaidooj.org/" },
      { title: "Raksha Bandhan", url: "http://www.raksha-bandhan.com/" },
      { title: "Durga Puja", url: "http://www.durga-puja.org/" },
      { title: "Karwa Chauth", url: "http://www.karwachauth.com/" },
      { title: "Pongal: Harvest Festival of South India", url: "http://www.pongalfestival.org/" },
      { title: "Baisakh: Harvest Festival of Punjab", url: "http://www.baisakhifestival.com/" },
      { title: "Lohri: Festival to Worship Fire", url: "http://www.lohrifestival.org/" },
      { title: "Onam: Homecoming of King Mahabali", url: "http://www.onamfestival.org/" },
      { title: "Teej: Dedicated to Shiva-Parvati", url: "http://www.teejfestival.org/" },
      { title: "Krishna Janmashtami", url: "http://www.krishnajanmashtami.com/" },
      { title: "Information on Temples", url: "http://www.templenet.com/" },
      { title: "Devotional Songs", url: "http://www.devotionalsongs.com/" },
      { title: "Puja", url: "http://www.archaka.com/" },
      { title: "Bhajan Kirtan", url: "http://www.bhajans.org/" },
      { title: "Temple Resources", url: "http://www.mandirnet.org/" },
      { title: "Information on Jyotir Lingas", url: "http://www.jyotirlinga.com/" },
      { title: "Worship Procedures by ISKCON", url: "http://www.deityworship.com/" },
      { title: "Sri Vaishnava - Ramanujacharya", url: "http://www.ramanuja.org/" },
      { title: "Krishna Science", url: "http://www.krishnascience.com/" },
      { title: "Transcendental Meditation", url: "http://www.alltm.org/" },
      { title: "Osho World", url: "http://www.oshoworld.com/" },
      { title: "Paintings of Vedic Gods", url: "http://www.sanatansociety.com/" },
      { title: "Martial Arts from Kerala", url: "http://www.kalarippayat.com/" },
      { title: "Indian Dance and Music", url: "http://www.artindia.net/" },
      { title: "Magazine For Indian Classical Music and Dance", url: "http://www.sruti.com/" },
      { title: "Deepali Ravi - BharatNatyam", url: "http://www.nadanam.com/" },
      { title: "Maitreya Buddha Project", url: "http://www.maitreyaproject.org/" },
      { title: "Moscow Vedic Temple & Cultural Center", url: "http://www.moscowtemple.org/" },
      { title: "Lord Subrahmanya Temples in Europe", url: "http://www.skandavale.org/" },
    ],
  },
  {
    id: "communities",
    title: "Communities",
    links: [
      { title: "Sharing the Universal Dharma", url: "http://www.vedicfriends.org/" },
      { title: "Soundarya Lahiri", url: "http://www.srimeru.org/" },
      { title: "Datta Yoga Center", url: "http://www.dycusa.org/" },
      { title: "Art Of Living", url: "http://www.artofliving.org/" },
      { title: "Students of Harish Johari", url: "http://www.sanatansociety.org/" },
      { title: "Mata Amritanandamayi Devi", url: "http://www.amma.org/" },
      { title: "Shri Satya Sai Baba", url: "http://www.sathyasai.org/" },
      { title: "Transcendental Meditation", url: "http://www.tm.org/" },
      { title: "Divya Yoga", url: "http://www.divyayoga.com/" },
      { title: "Yogacharya B.K.S. Iyengar", url: "http://www.bksiyengar.com/" },
      { title: "Bikram Yoga", url: "http://www.bikramyoga.com/" },
      { title: "Sahaja Yoga", url: "http://www.sahajayoga.org/" },
      { title: "Shakti Sadhana", url: "http://www.shaktisadhana.org/" },
      { title: "Bhagwan Swaminarayan - BAPS", url: "http://www.swaminarayan.org/" },
      { title: "ISKCON", url: "http://www.iskcon.org/" },
      { title: "Spiritual Teachings of Ancient India", url: "http://www.arshabodha.org/" },
      { title: "Upliftment of Brahmin Community", url: "http://www.dhanwantri.org/" },
      { title: "Classical Yoga Hindu Academy", url: "http://www.classicalyoga.org/" },
      { title: "Ashram - Path of Om Yoga meditation", url: "http://www.atmajyoti.org/" },
      { title: "International Nath Order", url: "http://www.nathorder.org/" },
      { title: "Hare Krishna Center For Vedic Studies", url: "http://www.gauranga.org/" },
      { title: "International Gita Society", url: "http://www.gita-society.com/" },
      { title: "Maharishi Vedic Community USA", url: "http://www.vedic-community.org/" },
      { title: "Mandala Yoga Ashram - UK", url: "http://www.mandalayoga.net/" },
      { title: "All World Gayatri Pariwar", url: "http://www.awgp.org/" },
      { title: "Friends of OSHO", url: "http://www.sannyas.net/" },
      { title: "Krishnamurti Information Network", url: "http://www.kinfonet.org/" },
    ],
  },
  {
    id: "political-ideologues",
    title: "Political Ideologues",
    links: [
      { title: "Mahatma Gandhi - Life, Work & Philosophy", url: "http://www.mkgandhi.org/" },
      { title: "Mahatma Gandhi - A 'Voilent' Pacifist", url: "http://www.gandhibapu.com/" },
      { title: "Vinayak Damodar Savarkar - 'Hindutva' Ideology", url: "http://www.savarkar.org/" },
      { title: "Shri Golwalkar - Ex RSS Chief", url: "http://www.golwalkarguruji.org/" },
    ],
  },
  {
    id: "organizations",
    title: "Organizations",
    links: [
      { title: "Rashtriya Swayamsevak Sangh", url: "http://www.rss.org/" },
      { title: "Vishwa Hindu Parishad", url: "http://www.vhp.org/" },
      { title: "Vishwa Hindu Parishad America", url: "http://www.vhp-america.org/" },
      { title: "Bajrang Dal", url: "http://www.hinduunity.com/" },
      { title: "Ekal Vidhyalaya", url: "http://www.ekalindia.org/" },
      { title: "Hindu Human Rights", url: "http://www.hinduhumanrights.org/" },
      { title: "Hindu Swayamsevak Sangh", url: "http://www.hssworld.org/" },
      { title: "Bharatiya Janata Party", url: "http://www.bjp.org/" },
      { title: "American Hindu Voice", url: "http://www.hinduamericanfoundation.org/" },
      { title: "Hindu Forum of Britain", url: "http://www.hinduforum.org/" },
      { title: "Monthly Magazine in UK", url: "http://www.thehinduvoice.com/" },
      { title: "Activities For Kids", url: "http://www.balagokulam.org/" },
      { title: "Friends Of India Society International", url: "http://www.fisiusa.org/" },
      { title: "Swadeshi Jagran Manch", url: "http://www.swadeshi.org/" },
      { title: "Kashmiri Hindu Liberation Army", url: "http://www.hindurashtra.org/" },
      { title: "Sri Jagannath Center - Jyotish", url: "http://www.srijagannath.org/" },
      { title: "Collective Voice of Hindu Society", url: "http://www.acharyasabha.org/" },
      { title: "Hindu Students Council", url: "http://www.hscnet.org/" },
      { title: "India Development and Relief Fund", url: "http://www.idrf.org/" },
      { title: "Infinity Foundation", url: "http://www.infinityfoundation.com/" },
      { title: "Youth Activities", url: "http://www.hinduyuva.org/" },
      { title: "Serving Hindus of North America", url: "http://www.hinduamerica.com/" },
      { title: "Let India Develop", url: "http://www.letindiadevelop.org/" },
      { title: "Hindu Heritage Endowment", url: "http://www.hheonline.org/" },
      { title: "Organization Promoting Sanskrit", url: "http://www.samskritabharati.org/" },
      { title: "International Forum for India's Heritage", url: "http://www.jaia-bharati.org/" },
    ],
  },
  {
    id: "news-magazines",
    title: "News & Magazines",
    links: [
      { title: "Daily Pioneer", url: "http://www.dailypioneer.com/" },
      { title: "National Daily From Chennai", url: "http://www.newstodaynet.com/" },
      { title: "Collection of Daily News", url: "http://www.sarvesamachar.com/" },
      { title: "RSS portal", url: "http://www.organiser.org/" },
      { title: "Hindu News from Kerala", url: "http://www.haindavakeralam.org/" },
      { title: "News Portal", url: "http://www.hinduvoice.net/" },
      { title: "News Portal (Jagruti)", url: "http://www.hindujagruti.org/" },
      { title: "Hindu Universe", url: "http://www.hindunet.com/" },
      { title: "Links to Hindu Activities", url: "http://www.hindulinks.org/" },
      { title: "Public Opinion Forum", url: "http://www.vigilonline.com/" },
      { title: "Hindu Vivek Kendra", url: "http://www.hvk.org/" },
      { title: "Vaishnava News Network", url: "http://www.vnn.org/" },
      { title: "Hinduism Today", url: "http://www.hinduismtoday.com/" },
      { title: "Quarterly by Maharishi Vedic Edu", url: "http://www.enlightenmenttoday.com/" },
      { title: "News From Indian Sub-Continent", url: "http://indiaview.wordpress.com/" },
      { title: "Magazine of Gayatri Pariwar", url: "http://www.akhandjyoti.org/" },
    ],
  },
  {
    id: "opinions-articles",
    title: "Opinions & Articles",
    links: [
      { title: "Voice of Dharma", url: "http://www.voiceofdharma.org/" },
      { title: "Quotes on Hinduism", url: "http://www.hinduwisdom.info/" },
      { title: "Pride of Indian Culture", url: "http://www.indpride.com/" },
      { title: "Archeological Evidence", url: "http://www.archaeologyonline.net/" },
      { title: "Indian Science and Technology", url: "http://www.indianscience.org/" },
      { title: "Indology - Gateway to Ancient India", url: "http://www.gosai.com/" },
      { title: "The Hindu Renaissance", url: "http://www.hindurenaissance.com/" },
      { title: "Francois Gautier - Journalist", url: "http://www.francoisgautier.com/" },
      { title: "Hindu Identity of India", url: "http://vivekajyoti.blogspot.com/" },
      { title: "Resume of Hindu Thought", url: "http://hinduthinktank.blogspot.com/" },
      { title: "Rajeev Srinivasan - Journalist", url: "http://rajeev2004.blogspot.com/" },
      { title: "Devoted to 'Bharat' and 'Dharma'", url: "http://www.satyameva-jayate.org/" },
      { title: "Indic Studies Foundation", url: "http://www.indicstudies.us/" },
      { title: "The Vedic Foundation", url: "http://www.thevedicfoundation.org/" },
      { title: "Preserve and Revive Hinduism", url: "http://www.hindusarise.com/" },
      { title: "Vedic Astronomy Enthusiast", url: "http://www.vedicastronomy.net/" },
      { title: "Dedicated To Bharat", url: "http://www.esamskriti.com/" },
      { title: "Indian Culture and History", url: "http://azygos.sulekha.com/" },
      { title: "Uniting Hindu Society Worldwide", url: "http://www.sanghparivar.org/" },
      { title: "Indian Leaders' Speeches", url: "http://www.theuniversalwisdom.org/" },
      { title: "Sangh Parivar Insider", url: "http://sangh.wordpress.com/" },
      { title: "Secular India", url: "http://indiasecular.wordpress.com/" },
      { title: "Faith, Culture and Politics", url: "http://indowave.tripod.com/" },
      { title: "News Analysis India", url: "http://www.newsanalysisindia.com/" },
      { title: "India Awakening", url: "http://ariseindiaarise.blogspot.com/" },
      { title: "Teesta Setalvad - Anti-India Activist", url: "http://teesta.blogspot.com/" },
      { title: "Communal Politics of Indian Congress", url: "http://truecongresspolitics.wordpress.com/" },
      { title: "Nehru Family", url: "http://www.nehrufamily.com/" },
      { title: "Gurumurthy - CA, Journalist", url: "http://www.gurumurthy.net/" },
      { title: "Foundation Against Continuing Terrorism", url: "http://factusa.blogspot.com/" },
      { title: "Basic Information on Indian Culture", url: "http://www.bharatwisdom.com/" },
      { title: "Current Affairs", url: "http://www.sandeepweb.com/" },
      { title: "Voice of Free Indian", url: "http://www.geocities.com/bharatvarsha1947/" },
      { title: "Indian Nation and its Heritage", url: "http://www.akhandbharat.org/" },
    ],
  },
  {
    id: "threats-challenges",
    title: "Threats & Challenges",
    links: [
      { title: "Crusade Watch", url: "http://www.crusadewatch.org/" },
      { title: "Christian Missionary Aggression", url: "http://www.christianaggression.org/" },
      { title: "History of Christianity in India", url: "http://www.hamsa.org/" },
      { title: "Missionary Agenda", url: "http://conversionagenda.blogspot.com/" },
      { title: "Christian Atrocities and Inquisitions", url: "http://www.burningcross.net/" },
      { title: "Islamic Terrorism in India", url: "http://islamicterrorism.wordpress.com/" },
      { title: "Human Rights Congress For Bangladesh Minorities", url: "http://www.hrcbm.org/" },
      { title: "Fate Of Kashmir Hindus", url: "http://www.panunkashmir.org/" },
      { title: "Kashmir - Paradise Turned Into Hell", url: "http://www.kashmir-information.com/" },
      { title: "Kashmiri Hindus 'Exiled' In Home Country", url: "http://www.kashmiri-pandit.org/" },
      { title: "Bengal Partition", url: "http://www.bengalvoice.com/" },
      { title: "Addressing Naxalite Menace", url: "http://naxalwatch.blogspot.com/" },
      { title: "Communist Party Marxist Terror", url: "http://cpmterror.blogspot.com/" },
      { title: "Communism Watch", url: "http://communismwatch.blogspot.com/" },
      { title: "Voice of Nationalist Hindus", url: "http://pseudosecularism.blogspot.com/" },
      { title: "Indian media accountability", url: "http://truthprevails.wordpress.com/" },
      { title: "Chindu Newspaper", url: "http://cbcnn.blogspot.com/" },
      { title: "South Asian Bleeding Hearts Association", url: "http://www.sabha.info/" },
      { title: "Sankaracharya Arrest Episode", url: "http://sankaracharyaarticles.blogspot.com/" },
      { title: "Kanchi Shankaracharya - Authentic Info", url: "http://www.kanchi-sathya.org/" },
      { title: "Govt Taking Over Temples", url: "http://www.savetemples.org/" },
      { title: "Global Hindu Heritage Foundation", url: "http://www.preservehinduism.org/" },
      { title: "Save Rama Setu", url: "http://saveramasetu.blogspot.com/" },
      { title: "Rama's Bridge", url: "http://www.bridgeofram.com/" },
      { title: "Rama Setu Information", url: "http://www.ramsethu.org/" },
      { title: "Online Hindu Holocaust Memorial Museum", url: "http://www.hinduholocaust.com/" },
      { title: "Holocaust Down the Timeline", url: "http://www.geocities.com/hindoo_humanist/" },
    ],
  },
];
